export Dentist from './dentist'
export Clinic from './clinic'
export Patient from './patient'
export Treatment from './treatment'
export DentistTimeslot from './dentist-timeslot'
export Appointment from './appointment'
export Report from './report'
export Token from './token'